### ISSUE TITLE
How can I override the default element style from Css.js

### ISSUE THREAD

**Issue by RossVertizan** [grizzthedj/react-bootstrap-dropdown-menu#12]
I love this component, exactly what I need, but how can I modify the styling to meet my requirements.

As far as I can see the styles (in my case for the TextTrigger) are set in the Css.js file and are then implemented on the element as the element style.  I see that there is a class __react_bs_dd_trigger_1 which is applied to the element and I can define that in my CSS, but I can't override the default settings for e.g. padding because the element.style CSS settings take precedence over the class CSS settings.

Could the elements be styled using the class names and a CSS file imported, which would allow for modification of the CSS file to customise the appearance to each use.

Many thanks in advance.

**Comment by grizzthedj** [comment]
@RossVertizan I can update the component so that the CSS as JS hash can be passed in as a prop. I did the same thing recently for the [react-json-to-html](https://github.com/grizzthedj/react-json-to-html) component. Should be able to add this in the next few days.

**Comment by grizzthedj** [comment]
@RossVertizan I have added the CSS prop and published version 1.1.20. The README is updated with the specifics, and you can see an example of how to use the new prop [here](https://grizzthedj.github.io/react-bootstrap-dropdown-menu/demo/public/cssoverride)

**Comment by RossVertizan** [comment]
@grizzthedj Superb, thank you.  I'll update and give it a go.

Again, many thanks for the quick turnaround.

**Comment by RossVertizan** [comment]
@grizzthedj OK, I have pulled the latest version and I have what I wanted, nearly.  But all good.

I followed the example, you provided:

`gear: {
        color: 'pink',
        padding: '24px'
      },
      menuContent: {
        backgroundColor: 'pink',
        padding: '24px'
      }`

at first I was a bit confused as to where to find the names of the formatting.  I looked through the code looking for anything "css.*", before realising that of course I could just look in the Css.js.   For anyone that comes behind me, the formatting classes are: pointer, disabledItem, gear, triangle, imageTrigger, textTrigger, menuItem, menuContent, show and separator.

I just needed the textTrigger formatting, which I implemented, but I got an error because there is a comparison with the icon color and that appears to need the gear class defined in the cssAsJs, so I added that in as well, and ended up with this:
`const cssAsJs = {
    gear: {
        color: 'pink',
        padding: '24px'
    },
    textTrigger: {
        color: "#cc0000",
        padding: "0 0.45rem",
        margin: "0 1rem",
        cursor: "pointer",
        border: "none",
        fontWeight: "normal",
        font: '12px "Open Sans"',
        minWidth: "70px"
    }
}`

I have two questions:
    1. I tried to implement a separator as follows
    `const cssAsJs = {
    gear: {
        color: 'pink',
        padding: '24px'
    },
    textTrigger: {
        color: "#cc0000",
        padding: "0 0.45rem",
        margin: "0 1rem",
        cursor: "pointer",
        border: "none",
        fontWeight: "normal",
        font: '12px "Open Sans"',
        minWidth: "70px"
    },
    separator: {
        width: '80%',
        color: "#CC0000",
        backgroundColor: "#CC0000",
        height: 1
    }
}`
 and:
`<DropdownMenu
                        triggerType='text'
                        trigger={user.name}
                        css={cssAsJs}
                    >
                        <MenuItem text='Edit Profile' location='/edit-profile' />
                        <MenuItem text='User Settings' location='/user-settings' />
                        <MenuItem text='Logout' onClick={logout} />
                        <MenuItem type='separator' css={cssAsJs}/>
                        <MenuItem text='Delete Account' onClick={() => deleteAccount(user.id)} />
                    </DropdownMenu>`
but this did not work - I expected to see a red separator line.

2.  How do I pass :hover CSS settings in JSON format, I want the textTrigger to get font-weight: bolder on hover, focus, active etc.

Sorry, don't know why my code has lost its carriage returns.

Again,

Many thanks,

Ross

**Comment by grizzthedj** [comment]
@RossVertizan I will have a look at the error you got, but to answer your 2 questions ...

1. Unfortunately at this moment, the `separator` is not being overridden if passed in the`css` prop. It is being ignored in the props, and using the values from the default `Css.js`. I can easily fix this so that it will be overridden as well.
2. Passing `hover` will not work in the current state(I don't think). Can you provide the CSS you would like to pass in for this, and I can add it? 

Also, if the `css` prop is passed to the `MenuItem` component, it will be ignored. I will also create the `css` prop for the `MenuItem` component as well.

**Comment by grizzthedj** [comment]
@RossVertizan I have fixed the bug you faced when not specifying `gear` in the CSS. I have also made it possible to override the `separator` in the CSS. You can see the example here: 

https://grizzthedj.github.io/react-bootstrap-dropdown-menu/demo/public/cssoverride

I have also added mouse events to the `DropdownMenu` so that you can do stuff when when mousing over and out of the `DropdownMenu` trigger. See the example of this here.

https://grizzthedj.github.io/react-bootstrap-dropdown-menu/demo/public/texttrigger

This was all just pushed in version 1.1.22. Going to reopen this, and wait for your comment to see if this resolves your issue

**Comment by RossVertizan** [comment]
@grizzthedj Wow, so much to report on:

1. Thank you, the separator CSS override works as expected.  Though the example code is missing the Settings and the separator menu items.

2. I no longer have to specify gear in the CSS override.

3. I have been able to use the onMouseover and onMouseout events to change the styling of the textTrigger.  I had to play around to get it working with the functional style that React now uses, using useState and useEffect, but aftre some silly errors I got it working.  I found [this SO article to follow.](https://stackoverflow.com/questions/58073526/change-style-on-mouseover-event-in-reactjs-functional-component).  While this helped me to get it working, a number of the answers refer to the fact that using the mouse events is an expensive way of doing it, and I have been wondering why you use element styling, rather than simply assigning each element a CSS class and then using CSS to do the styling?

Thanks for your support.

**Comment by grizzthedj** [comment]
@RossVertizan Glad to hear it is working, and thanks for letting me know about the missing MenuItems in the example. It is fixed now. 

I terms of the CSS, the "CSS as JS" approach on the elements was kind of an experiment. As this component started to evolve, I started to see some of the limitations. This part of the implementation needs to be reworked so that CSS classes can be used(to your point). Will hopefully find some time to do this early in the new year. PR's are always welcome too! ;)
